name: sim-smoke

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  run-sim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Start a test HTTP collector
        run: |
          python - <<'PY'
import asyncio
from aiohttp import web
async def ingest(request):
    data = await request.json()
    return web.json_response({"ok": True})
app = web.Application()
app.add_routes([web.post('/ingest', ingest)])
web.run_app(app, port=8080)
PY
        background: true
      - name: Run 100 sensors over HTTP for 30s
        run: |
          python run_sim.py --count 20 --transport http --http-url http://localhost:8080/ingest --rate 2 --duration 30 --log-csv out.csv
